### ISSUE TITLE
esl.connection.createInbound is not a function

### ISSUE THREAD

**Issue by fdl333** [englercj/node-esl#107]
I tried your very simple script and I get this message:
esl.connection.createInbound is not a function

Script:

const esl = require('modesl');

const connectionOptions = {
    host: '127.0.0.1',
    port: 8021,
};

const connection = esl.Connection.createInbound(connectionOptions, 'ClueCon', function ()
{
    connection.api('status', function (res)
    {
        console.log(res.getBody());
    });
});

**Comment by wfleischer** [comment]
The createInbound function has been introduced with version 2.0 (see https://github.com/englercj/node-esl/blob/master/UPGRADE.md). It has not been released though. So you are trying updated examples on an older release.

**Comment by batbrain9392** [comment]
@fdl333 maybe this'd help -
```js
var esl = require('modesl'),
conn = new esl.Connection('127.0.0.1', 8021, 'ClueCon', function() {
    conn.api('status', function(res) {
        //res is an esl.Event instance
        console.log(res.getBody());
    });
});
```

**Comment by fdl333** [comment]
Thank you! Will try immediately!

Francesco Facco de Lagarda

**Comment by fdl333** [comment]
YUP! It works!
Thanks sooo much!
