### ISSUE TITLE
no issue, just help needed

### ISSUE THREAD

**Issue by celevra** [englercj/node-esl#41]
Hi, 

i'm trying to listen to the conference::maintenance (https://wiki.freeswitch.org/wiki/Mod_conference#Event_Socket_Use) events like this
```

var esl = require('modesl'),
conn = new esl.Connection('127.0.0.1', 8021, 'ClueCon', function() {
    conn.api('status', function(res) {
        //res is an esl.Event instance
        console.log(res.getBody());
    });
    conn.subscribe('conference::maintenance');
});

conn.on('esl::event::conference::maintenance::**', function(evt) {
     console.log('Event:', evt.getHeader('Event-Name'));
});
```

but i don't get anything back, also just esl:event::** gives only channel events, is there anything special i have todo?

thank you for your help

regards

**Comment by englercj** [comment]
Interesting, I wonder if the event name having `::` is doing something weird? It has been years since I worked with fsw and this lib actively (sorry!).

I would try `conn.subscribe();` (subscribes to all messages) and see what listening to `esl::event::**` gives you.

**Comment by celevra** [comment]
that is working it is type CUSTOM and subclass conference::maintenance
so i subscribe to custom and filter with js on the subclass
thank you very much for your help

**Comment by englercj** [comment]
@celevra Ah! No problem!
