### ISSUE TITLE
node-esl for LB

### ISSUE THREAD

**Issue by murugannode** [englercj/node-esl#44]
node-els is fine with one freeswitch server if i run two or more freeswitch with opensip(SIP Proxy ) how i can handle ESL

**Comment by englercj** [comment]
This module was intentionally meant to be low-level. ALl it does is implement a JS API into ESL. You can connect to multiple FSWs or just one. How you build clustering and synchronization is entirely up to you and your application. This library doesn't provide any of that.

**Comment by englercj** [comment]
Closing for now, let me know if I need to reopen.
