### ISSUE TITLE
CHANNEL_EXECUTE_COMPLETE never received

### ISSUE THREAD

**Issue by davehorton** [englercj/node-esl#50]
I am wondering whether this project is active and, if so, are you open to pull requests?

I have noticed that when I execute the freeswitch 'conference' application that I get a CHANNEL_EXECUTE event but freeswitch actually never sends a CHANNEL_EXECUTE_COMPLETE event in this case, and therefore my callback passed to Callback.execute never gets called.  

I don't see this as an issue in the esl library, but it means I will need to track things at a higher level in my application.  This would be enabled quite easily if I could get back the Event-UUID the _doExec creates on the outgoing request.  Can I submit a PR for this?

**Comment by englercj** [comment]
The project isn't necessarily "active" sine I don't work with FSW anymore, but I am extremely active on GitHub and always respond to issues and PRs here.

**Comment by englercj** [comment]
Closed by merging #51.
