### ISSUE TITLE
Clarification needed for using this module

### ISSUE THREAD

**Issue by vijayaa** [englercj/node-esl#61]
We are planning to using this module to make connection to freeswitch and place users in conference call by executing an api command 

 **conference testconf dial {originate_timeout=30}user/1001 1234567890 FreeSWITCH_Conference**
Will be OK if there are many conferences parallelly

**Comment by aalexgabi** [comment]
@vijayaa I'm not sure I understand your question. Yes FreeSWITCH can handle multiple conferences in the same time. Yes you can use node-esl to join multiple legs with a conference or initiate legs for a specific conference.

There may be CPU performance issues with your FreeSWITCH server if you want to create hundreds of conferences with hundreds of legs.

**Comment by vijayaa** [comment]
OK. Thank you
