### ISSUE TITLE
How to handle connection errors?

### ISSUE THREAD

**Issue by babakyakhchali** [englercj/node-esl#68]
Hi
how can network errors be handled? something like this:
Error: connect ECONNREFUSED 192.168.2.18:8021
constructor only gets a callback which is called after successful connection. but what if esl server is down or not reachable?

**Comment by englercj** [comment]
Listen for the `error` event. It will emit anytime an error happens:

```js
var conn = new esl.Connection(...);

conn.on('error', function (err) {
    // handle err
}
```

**Comment by babakyakhchali** [comment]
thank you
you are right and it is working.
