### ISSUE TITLE
Can't Install version 2.0.0

### ISSUE THREAD

**Issue by bliteknight** [englercj/node-esl#83]
Trying to use this module, but the latest built in npm is 1.2.1

What do I need to do to get version 2.0.0 because the example on how to use it does not work in 1.2.1

Thanks.

**Comment by englercj** [comment]
v2 has not yet been released.

You can look at v1.2.1 examples if you need to still though: https://github.com/englercj/node-esl/tree/v1.2.1

**Comment by bliteknight** [comment]
ok thanks, awesome work by the way.
